//
//  Countries.swift
//  MainCRM
//
//  Created by Main on 21.03.2025.
//

import Foundation

enum Countries: String, CaseIterable {
    case AU = "Австралия"
    case AT = "Австрия"
    case AZ = "Азербайджан"
    case AR = "Аргентина"
    case AM = "Армения"
    case BD = "Бангладеш"
    case BY = "Беларусь"
    case BE = "Бельгия"
    case BG = "Болгария"
    case BO = "Боливия"
    case BR = "Бразилия"
    case GB = "Великобритания"
    case HU = "Венгрия"
    case VE = "Венесуэла"
    case VN = "Вьетнам"
    case DE = "Германия"
    case HK = "Гонконг"
    case GR = "Греция"
    case GE = "Грузия"
    case DK = "Дания"
    case EG = "Египет"
    case IL = "Израиль"
    case IN = "Индия"
    case ID = "Индонезия"
    case IE = "Ирландия"
    case IS = "Исландия"
    case ES = "Испания"
    case IT = "Италия"
    case KZ = "Казахстан"
    case CA = "Канада"
    case CO = "Колумбия"
    case LV = "Латвия"
    case LT = "Литва"
    case MY = "Малайзия"
    case MX = "Мексика"
    case NP = "Непал"
    case NL = "Нидерланды"
    case NZ = "Новая Зеландия"
    case NO = "Норвегия"
//    case PK = "Пакистан"
//    case PE = "Перу"
//    case PL = "Польша"
//    case PT = "Португалия"
//    case KR = "Корея"
//    case RU = "Россия"
//    case RO = "Румыния"
//    case RS = "Сербия"
//    case SK = "Словакия"
//    case SI = "Словения"
//    case US = "США"
//    case TJ = "Таджикистан"
//    case TH = "Таиланд"
//    case TR = "Турция"
//    case UZ = "Узбекистан"
//    case UA = "Украина"
//    case UY = "Уругвай"
//    case FJ = "Фиджи"
//    case PH = "Филиппины"
//    case FI = "Финляндия"
//    case FR = "Франция"
//    case HR = "Хорватия"
//    case ME = "Черногория"
//    case CZ = "Чехия"
//    case CL = "Чили"
//    case CH = "Швейцария"
//    case SE = "Швеция"
//    case LK = "Шри-Ланка"
//    case EC = "Эквадор"
//    case EE = "Эстония"
//    case ZA = "ЮАР"
//    case JP = "Япония"
}
